import type { Product } from "@/components/product-card";
import type { GalleryImage } from "@/components/gallery-grid";

export const companyInfo = {
  name: "Yazh Pure Life",
  tagline: "RO Water Purifier - Sales & Services",
  subTagline: "Domestic & Commercial",
  certification: "ISO 9001:2015 Certified",
  rating: "4.8",
  reviews: "1,014",
  website: "www.yazhpurelife.in",
  phone1: "+91-97865 69973",
  phone2: "+91-80980 94111",
  phone1Href: "tel:+919786569973",
  phone2Href: "tel:+918098094111",
  whatsapp: "919786569973",
  email: "yazhpurelife@gmail.com",
  emailHref: "mailto:yazhpurelife@gmail.com",
  paymentNumber: "+91-97865 69973",
  addressLines: [
    "No.19, Venkateshwara Nagar, Teachers Colony",
    "Kadappa Road, Kolathur, Chennai",
    "Tamil Nadu - 600099",
  ],
  branches: ["Kolathur", "Avadi", "Tada"],
  socials: {
    facebook: "https://www.facebook.com/yazhpurelifeRO/",
    twitter: "https://twitter.com/LifeYazh",
    youtube: "https://www.youtube.com/channel/UC_T8fMK5YR-Mky3GwYTCT3g",
  },
};

export const products: Product[] = [
  {
    id: "1",
    name: "YPL Dolphin",
    price: 8800,
    image: "/products/YPL%20DOLPHIN%20.jpg",
    category: "Home Use",
    type: "Only RO",
    stages: "5",
    capacity: "9L Detachable",
    description: "YPL Dolphin is a compact 5-stage only RO purifier for home use with 9L detachable storage.",
    features: ["Only RO purification", "5-stage filtration", "9L detachable storage", "Suitable for home use"],
    specifications: [
      { label: "Type", value: "Only RO" },
      { label: "Stages", value: "5" },
      { label: "Storage", value: "9L Detachable" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "2",
    name: "YPL Lily",
    price: 9800,
    image: "/products/YPL%20LILY.png",
    category: "Home Use",
    type: "RO + Minerals",
    stages: "5",
    capacity: "10L Detachable",
    description: "YPL Lily combines RO purification with minerals in a 5-stage system and 10L detachable storage.",
    features: ["RO + Minerals", "5-stage filtration", "10L detachable storage", "Home RO model"],
    specifications: [
      { label: "Type", value: "RO + Minerals" },
      { label: "Stages", value: "5" },
      { label: "Storage", value: "10L Detachable" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "3",
    name: "YPL Aqua 2090",
    price: 9800,
    image: "/products/YPL%20Aqua%202090.jpg",
    category: "Home Use",
    type: "RO + Minerals",
    stages: "5",
    capacity: "10L Detachable",
    description: "YPL Aqua 2090 is a 5-stage RO + Minerals purifier with 10L detachable storage for everyday home use.",
    features: ["RO + Minerals", "5-stage filtration", "10L detachable storage", "Domestic water purifier"],
    specifications: [
      { label: "Type", value: "RO + Minerals" },
      { label: "Stages", value: "5" },
      { label: "Storage", value: "10L Detachable" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "4",
    name: "YPL Pure X",
    price: 10300,
    image: "/products/YPL%20PURE%20X.png",
    category: "Home Use",
    type: "RO + Minerals + Alkaline",
    stages: "6",
    capacity: "10L Detachable",
    description: "YPL Pure X adds alkaline support to RO + Minerals purification with 6-stage filtration.",
    features: ["RO + Minerals + Alkaline", "6-stage filtration", "10L detachable storage", "Home use purifier"],
    specifications: [
      { label: "Type", value: "RO + Minerals + Alkaline" },
      { label: "Stages", value: "6" },
      { label: "Storage", value: "10L Detachable" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "5",
    name: "YPL Mirage",
    price: 10800,
    image: "/products/YPL%20Mirage%20.png",
    category: "Home Use",
    type: "RO + UV + Minerals + Alkaline",
    stages: "7",
    capacity: "12L",
    description: "YPL Mirage is a 7-stage RO + UV purifier with minerals, alkaline support, and 12L storage.",
    features: ["RO + UV + Minerals + Alkaline", "7-stage filtration", "12L storage", "Domestic RO purifier"],
    specifications: [
      { label: "Type", value: "RO + UV + Minerals + Alkaline" },
      { label: "Stages", value: "7" },
      { label: "Storage", value: "12L" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "6",
    name: "YPL Emira",
    price: 10800,
    image: "/products/YPL%20EMIRA.jpg",
    category: "Home Use",
    type: "RO + Minerals + Alkaline + Tank UV",
    stages: "7",
    capacity: "10L",
    description: "YPL Emira includes RO, minerals, alkaline support, and Tank UV in a 7-stage home purifier.",
    features: ["RO + Minerals + Alkaline + Tank UV", "7-stage filtration", "10L storage", "Home use model"],
    specifications: [
      { label: "Type", value: "RO + Minerals + Alkaline + Tank UV" },
      { label: "Stages", value: "7" },
      { label: "Storage", value: "10L" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "7",
    name: "YPL Aqua 9090",
    price: 10800,
    image: "/products/YPL%20Aqua%209090.jpg",
    category: "Home Use",
    type: "RO + UV + Minerals + Alkaline",
    stages: "6",
    capacity: "10L",
    description: "YPL Aqua 9090 provides RO + UV + Minerals + Alkaline purification in a 6-stage setup.",
    features: ["RO + UV + Minerals + Alkaline", "6-stage filtration", "10L storage", "Domestic purifier"],
    specifications: [
      { label: "Type", value: "RO + UV + Minerals + Alkaline" },
      { label: "Stages", value: "6" },
      { label: "Storage", value: "10L" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "8",
    name: "YPL Sky",
    price: 11800,
    image: "/products/YPL%20Sky.jpg",
    category: "Home Use",
    type: "RO + Tank UV + Minerals",
    stages: "7",
    capacity: "7.5L SS / 9L",
    description: "YPL Sky is a 7-stage RO purifier with Tank UV, minerals, and 7.5L SS / 9L storage options.",
    features: ["RO + Tank UV + Minerals", "7-stage filtration", "7.5L SS / 9L storage", "Home use purifier"],
    specifications: [
      { label: "Type", value: "RO + Tank UV + Minerals" },
      { label: "Stages", value: "7" },
      { label: "Storage", value: "7.5L SS / 9L" },
      { label: "Category", value: "Home Use" },
    ],
  },
  {
    id: "9",
    name: "G-Series",
    price: 11800,
    originalPrice: 13990,
    image: "/products/G%20-%20Series.jpg",
    category: "Home Use",
    type: "RO + Alkaline + Zn + Tank UV",
    stages: "8",
    capacity: "10L",
    isi: true,
    description: "G-Series is an ISI-marked 8-stage RO purifier with alkaline, zinc, Tank UV, and 10L storage.",
    features: ["RO + Alkaline + Zn + Tank UV", "8-stage filtration", "10L storage", "ISI marked"],
    specifications: [
      { label: "Type", value: "RO + Alkaline + Zn + Tank UV" },
      { label: "Stages", value: "8" },
      { label: "Storage", value: "10L" },
      { label: "ISI", value: "Yes" },
    ],
  },
  {
    id: "10",
    name: "Prolife Viber",
    price: 12800,
    originalPrice: 15990,
    image: "/products/Prolife%20Viber.jpg",
    category: "Home Use",
    type: "RO + UV + Alkaline + TDS",
    stages: "8",
    capacity: "12L",
    isi: true,
    description: "Prolife Viber is an ISI-marked 8-stage purifier with RO, UV, alkaline, TDS support, and 12L storage.",
    features: ["RO + UV + Alkaline + TDS", "8-stage filtration", "12L storage", "ISI marked"],
    specifications: [
      { label: "Type", value: "RO + UV + Alkaline + TDS" },
      { label: "Stages", value: "8" },
      { label: "Storage", value: "12L" },
      { label: "ISI", value: "Yes" },
    ],
  },
  {
    id: "11",
    name: "Prolife Fiesta",
    price: 13800,
    originalPrice: 16990,
    image: "/products/PROLIFE%20FIESTA.jpg",
    category: "Home Use",
    type: "RO + UV + UF + Minerals + Copper + TDS + Alkaline",
    stages: "10",
    capacity: "12L",
    isi: true,
    description: "Prolife Fiesta is an ISI-marked 10-stage purifier with RO, UV, UF, minerals, copper, TDS, and alkaline support.",
    features: ["RO + UV + UF + Minerals + Copper + TDS + Alkaline", "10-stage filtration", "12L storage", "ISI marked"],
    specifications: [
      { label: "Type", value: "RO + UV + UF + Minerals + Copper + TDS + Alkaline" },
      { label: "Stages", value: "10" },
      { label: "Storage", value: "12L" },
      { label: "ISI", value: "Yes" },
    ],
  },
  {
    id: "12",
    name: "YPL Purelife (Hot & Cold)",
    price: 18800,
    image: "/products/YPL-PURELIFE-HOT-COLD.jpeg",
    category: "Hot & Cold",
    type: "RO Hot & Cold",
    stages: "-",
    capacity: "Hot 1L / Cold 0.5L / Normal 6L",
    description: "YPL Purelife Hot & Cold provides RO purified hot, cold, and normal water from one unit.",
    features: ["RO Hot & Cold", "Hot 1L storage", "Cold 0.5L storage", "Normal 6L storage"],
    specifications: [
      { label: "Type", value: "RO Hot & Cold" },
      { label: "Hot Storage", value: "1L" },
      { label: "Cold Storage", value: "0.5L" },
      { label: "Normal Storage", value: "6L" },
    ],
  },
  {
    id: "13",
    name: "YPL Whale 25",
    price: 18800,
    image: "/products/YPL%20WHALE_25.jpg",
    category: "Commercial",
    type: "Only RO",
    stages: "5",
    capacity: "25L",
    description: "YPL Whale 25 is a 25L only RO purifier for commercial water needs.",
    features: ["Only RO purification", "5-stage filtration", "25L storage", "Commercial model"],
    specifications: [
      { label: "Type", value: "Only RO" },
      { label: "Stages", value: "5" },
      { label: "Storage", value: "25L" },
      { label: "Category", value: "Commercial" },
    ],
  },
];

const galleryFiles = [
  { file: "YPL AQUA DIGI.png" },
  { file: "YPL AQUA 2090.png" },
  { file: "YPL-PURELIFE-HOT-COLD.jpg", name: "YPL PURELIFE (Hot & Cold)" },
  { file: "YPL 50 LPH RO.jpg" },
  { file: "YPL-WAVE-5G-HOT-COLD.png", name: "YPL WAVE 5G (Hot & Cold)" },
  { file: "YPL SEVEN X.png" },
  { file: "YPL AQUATICA.png" },
  { file: "YPL WATER LEEXY.png" },
  { file: "YPL MERLIN MATRIX.png" },
  { file: "YPL DOLPHIN.png" },
  { file: "YPL-GRAND-PLUS.png", name: "YPL GRAND+" },
  { file: "YPL NEXUS BRIO.jpg" },
  { file: "YPL PROLIFE.png" },
  { file: "YPL PROLIFE PIESTA.jpg" },
  { file: "YPL KAIROX.png" },
  { file: "YPL CHROME.png" },
  { file: "YPL PURE.png" },
  { file: "YPL AQUA PHOENIX P90.png" },
  { file: "YPL ALICA.png" },
  { file: "YPL MISTY PURE.png" },
  { file: "YPL WHALE_25.png" },
  { file: "YPL AQUA CYCLONE_.png" },
];

export const galleryImages: GalleryImage[] = galleryFiles.map((item) => {
  const name = (item.name ?? item.file)
    .replace(/\.(png|jpg|jpeg|webp)$/i, "")
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return {
    src: `/gallery/${encodeURIComponent(item.file)}`,
    alt: name,
    name,
    category: "Yazh Pure Life",
  };
});
