import type { Product } from "@/components/product-card";
import type { GalleryImage } from "@/components/gallery-grid";

export const products: Product[] = [
  {
    id: "1",
    name: "AquaPure RO + UV + UF",
    price: 12999,
    originalPrice: 18999,
    image: "https://images.unsplash.com/photo-1624628639856-100bf817fd35?w=600&h=600&fit=crop",
    category: "Home RO",
    capacity: "12 Liters",
    description:
      "Advanced 7-stage water purification system with RO, UV, and UF technology. Perfect for Indian homes with TDS levels up to 2000 ppm. Features mineralizer technology that adds essential minerals back to purified water.",
    features: [
      "7-Stage Purification Process",
      "TDS Controller",
      "Mineral Cartridge",
      "UV LED Indicator",
      "Full Tank Auto Shut-off",
      "Food Grade ABS Plastic Body",
      "1 Year Warranty",
      "Free Installation",
    ],
    specifications: [
      { label: "Purification Method", value: "RO + UV + UF" },
      { label: "Storage Capacity", value: "12 Liters" },
      { label: "Input TDS Range", value: "Up to 2000 ppm" },
      { label: "Purification Rate", value: "15 L/hr" },
      { label: "Voltage", value: "220-240V AC" },
      { label: "Dimensions", value: "40 x 25 x 52 cm" },
    ],
  },
  {
    id: "2",
    name: "CrystalClear UV Purifier",
    price: 6499,
    originalPrice: 9999,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
    category: "UV Purifier",
    capacity: "8 Liters",
    description:
      "Compact UV water purifier ideal for municipal water with low TDS. Uses powerful UV technology to eliminate 99.9% of bacteria, viruses, and other microorganisms. Energy efficient with sleek design.",
    features: [
      "UV Purification Technology",
      "Compact Design",
      "Low Power Consumption",
      "Auto UV Fail Alert",
      "Stainless Steel Storage Tank",
      "LED Indicators",
      "Easy Maintenance",
      "2 Year Warranty",
    ],
    specifications: [
      { label: "Purification Method", value: "UV" },
      { label: "Storage Capacity", value: "8 Liters" },
      { label: "Input TDS Range", value: "Up to 200 ppm" },
      { label: "UV Lamp Life", value: "8000 hours" },
      { label: "Voltage", value: "220-240V AC" },
      { label: "Dimensions", value: "32 x 22 x 45 cm" },
    ],
  },
  {
    id: "3",
    name: "Industrial RO Plant 500 LPH",
    price: 89999,
    originalPrice: 125000,
    image: "https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?w=600&h=600&fit=crop",
    category: "Industrial",
    capacity: "500 Liters/Hour",
    description:
      "High-capacity industrial RO plant designed for factories, schools, and commercial establishments. Features robust stainless steel construction with automatic operation and multiple safety features.",
    features: [
      "Automatic Operation",
      "High Recovery Rate",
      "Low Maintenance Design",
      "Stainless Steel Frame",
      "Multiple Stage Filtration",
      "Pressure Gauges & Flow Meters",
      "Anti-Scaling Technology",
      "1 Year AMC Included",
    ],
    specifications: [
      { label: "Purification Method", value: "Industrial RO" },
      { label: "Output Capacity", value: "500 LPH" },
      { label: "Input TDS Range", value: "Up to 3000 ppm" },
      { label: "Recovery Rate", value: "60-70%" },
      { label: "Power", value: "1.5 HP Motor" },
      { label: "Dimensions", value: "120 x 60 x 150 cm" },
    ],
  },
  {
    id: "4",
    name: "AquaSoft Water Softener",
    price: 24999,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1585687433095-e87bd2827ffa?w=600&h=600&fit=crop",
    category: "Water Softener",
    capacity: "Whole House",
    description:
      "Premium whole-house water softener that removes hardness minerals from water. Protects appliances, improves skin and hair health, and reduces scaling in pipes. Fully automatic regeneration.",
    features: [
      "Automatic Regeneration",
      "Digital Control Valve",
      "High Flow Rate",
      "Salt Saving Technology",
      "Compact Design",
      "Low Maintenance",
      "Protects Appliances",
      "5 Year Tank Warranty",
    ],
    specifications: [
      { label: "Technology", value: "Ion Exchange" },
      { label: "Flow Rate", value: "2000 LPH" },
      { label: "Hardness Removal", value: "Up to 500 ppm" },
      { label: "Resin Volume", value: "25 Liters" },
      { label: "Salt Capacity", value: "50 kg" },
      { label: "Dimensions", value: "35 x 35 x 100 cm" },
    ],
  },
  {
    id: "5",
    name: "PureMax RO + Alkaline",
    price: 15999,
    originalPrice: 22999,
    image: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&h=600&fit=crop",
    category: "Home RO",
    capacity: "10 Liters",
    description:
      "Premium alkaline RO water purifier that not only purifies but also adds healthy alkaline minerals. Provides pH-balanced drinking water that supports overall health and wellness.",
    features: [
      "8-Stage Purification",
      "Alkaline Technology",
      "Copper Infusion",
      "Smart LED Display",
      "Filter Change Alerts",
      "Child Lock Feature",
      "Quick Change Filters",
      "3 Year Warranty",
    ],
    specifications: [
      { label: "Purification Method", value: "RO + UV + Alkaline" },
      { label: "Storage Capacity", value: "10 Liters" },
      { label: "Output pH Level", value: "8.0 - 9.5" },
      { label: "Input TDS Range", value: "Up to 2500 ppm" },
      { label: "Voltage", value: "220-240V AC" },
      { label: "Dimensions", value: "38 x 24 x 50 cm" },
    ],
  },
  {
    id: "6",
    name: "Commercial RO 100 LPH",
    price: 45999,
    originalPrice: 65000,
    image: "https://images.unsplash.com/photo-1563351672-62b74891a28a?w=600&h=600&fit=crop",
    category: "Commercial",
    capacity: "100 Liters/Hour",
    description:
      "Perfect for restaurants, offices, and small businesses. This commercial RO system provides high-quality purified water with consistent output. Features automatic flushing and easy maintenance.",
    features: [
      "Automatic Flushing",
      "High Pressure Pump",
      "Pre-Filter Assembly",
      "TDS Reduction up to 95%",
      "Compact Frame Design",
      "Low Noise Operation",
      "Easy Filter Access",
      "1 Year Warranty + AMC",
    ],
    specifications: [
      { label: "Purification Method", value: "Commercial RO" },
      { label: "Output Capacity", value: "100 LPH" },
      { label: "Input TDS Range", value: "Up to 2500 ppm" },
      { label: "Recovery Rate", value: "50-60%" },
      { label: "Power", value: "0.5 HP Motor" },
      { label: "Dimensions", value: "80 x 45 x 100 cm" },
    ],
  },
];

export const galleryImages: GalleryImage[] = [
  {
    src: "https://images.unsplash.com/photo-1624628639856-100bf817fd35?w=600&h=600&fit=crop",
    alt: "Home RO Water Purifier",
    name: "AquaPure RO System",
    category: "Home Purifier",
  },
  {
    src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
    alt: "UV Water Purifier",
    name: "CrystalClear UV",
    category: "UV Purifier",
  },
  {
    src: "https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?w=600&h=600&fit=crop",
    alt: "Industrial Water Plant",
    name: "Industrial RO Plant",
    category: "Industrial",
  },
  {
    src: "https://images.unsplash.com/photo-1585687433095-e87bd2827ffa?w=600&h=600&fit=crop",
    alt: "Water Softener System",
    name: "AquaSoft Softener",
    category: "Water Softener",
  },
  {
    src: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&h=600&fit=crop",
    alt: "Alkaline RO System",
    name: "PureMax Alkaline",
    category: "Alkaline RO",
  },
  {
    src: "https://images.unsplash.com/photo-1563351672-62b74891a28a?w=600&h=600&fit=crop",
    alt: "Commercial RO System",
    name: "Commercial RO 100 LPH",
    category: "Commercial",
  },
  {
    src: "https://images.unsplash.com/photo-1520880867055-1e30d1cb001c?w=600&h=600&fit=crop",
    alt: "Water Filter Cartridges",
    name: "Filter Cartridges",
    category: "Accessories",
  },
  {
    src: "https://images.unsplash.com/photo-1527689638836-411945a2b57c?w=600&h=600&fit=crop",
    alt: "Water Testing",
    name: "Water Quality Testing",
    category: "Services",
  },
  {
    src: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600&h=600&fit=crop",
    alt: "Installation Service",
    name: "Professional Installation",
    category: "Services",
  },
];
